#!/usr/bin/python3

import sys
import re
import os
import json
import unicodedata
from datetime import datetime
import gzip
import random

nicemap = {
    "jagermeister": "jägermeister",
    "sweet vermouth": "vermouth (sweet)",
    "dry vermouth": "vermouth (dry)",
    "blue curacao": "curaçao (blue)",
    "curacao": "curaçao",
    "cold coffee": "coffee (cold)",
    "vanilla ice cream": "ice cream (vanilla)",
    "ground cinnamon": "cinnamon (ground)",
    "cinnamon stick": "cinnamon (stick)",
    "gold tequila": "tequila (gold)",
    "sloe gin": "gin (sloe)",
    "goldschlager": "goldschläger",
    "cream sherry": "sherry (cream)",
    "dry sherry": "sherry (dry)",
    "white wine": "wine (white)",
    "red wine": "wine (red)",
    "green chartreuse": "chartreuse (green)",
    "sweet/sour mix": "sour mix",
    "citron vodka": "vodka (citrus)",
    "citrus vodka": "vodka (citrus)",
    "currant vodka": "vodka (currant)",
    "mandarin vodka": "vodka (mandarin)",
    "vodka 100 proof": "vodka",
    "tequila premium": "tequila (premium)",
    "rum (dark) jamaican": "rum (dark jamaican)",
}


def fraction_pretify(instruction):
    if "/" not in instruction:
        return instruction
    m = re.search(r"\b(\d+/\d+)\b", instruction)
    if not m:
        return instruction
    fv_map = {
        "1/2": "VULGAR FRACTION ONE HALF",
        "1/3": "VULGAR FRACTION ONE THIRD",
        "2/3": "VULGAR FRACTION TWO THIRDS",
        "1/4": "VULGAR FRACTION ONE QUARTER",
        "3/4": "VULGAR FRACTION THREE QUARTERS",
        "1/5": "VULGAR FRACTION ONE FIFTH",
        "2/5": "VULGAR FRACTION TWO FIFTHS",
        "3/5": "VULGAR FRACTION THREE FIFTHS",
        "4/5": "VULGAR FRACTION FOUR FIFTHS",
        "1/6": "VULGAR FRACTION ONE SIXTH",
        "5/6": "VULGAR FRACTION FIVE SIXTHS",
        "1/8": "VULGAR FRACTION ONE EIGHTH",
        "3/8": "VULGAR FRACTION THREE EIGHTHS",
        "5/8": "VULGAR FRACTION FIVE EIGHTHS",
        "7/8": "VULGAR FRACTION SEVEN EIGHTHS",
        "1/16": "VULGAR FRACTION ONE SIXTEENTH",
    }
    name = fv_map[m.group(1)]
    try:
        new_instruction = instruction.replace(m.group(1), unicodedata.lookup(name))
    except KeyError:
        #print("Can't find", name)
        return instruction
    return new_instruction

class NonCanonicalIngredient(Exception): pass
class MakesNoSense(Exception): pass


def add_ingredient(ingred):
    if ingred not in canonical_ingredients:
        raise NonCanonicalIngredient(ingred)
    ingredients.add(ingred)


canonical_ingredients = dict()
with open("ingredients") as ingred:
    for line in ingred:
        t = line[0]
        name = line[2:].strip()

        canonical_ingredients[name] = t

ingredient_frequency = dict()
all_ingredients = set()
recipe_book = list()
for drink_number, filename in enumerate(os.listdir("recipes-clean")):
    if filename.startswith("."): continue
    with open(os.path.join("recipes-clean", filename)) as f:
        try:
            description = dict()
            ingredients = set()
            glasses = set()
            prepare_instructions = list()
            consume_instructions = list()


            glassline = f.readline().strip()
            glassline = glassline.replace("CordialOrBrandySnifter", "Cordial")
            m = re.match(r"\[genericglass ([A-Z][a-zA-Z ]*)([^]]*)\] Serving Glass: (.*)", glassline)
            if not m: raise ValueError(glassline)
            glass_id, glass_id_ext, glass_name = m.groups()
            if glass_id_ext:
                if glass_name.replace(" ", "") != glass_id + glass_id_ext:
                    print(m.groups(), repr(glassline))
            glass_id = glass_id.lower().replace("noice", "")
            if "salted" in glass_id:
                glass_id = "salted " + glass_id.replace("salted", "")
            if glass_id.endswith(("mug",)):
                glasses.add(glass_id)
            else:
                glasses.add(glass_id + " glass")
            if glass_id_ext:
                if glass_id_ext == "1/2FillIce":
                    prepare_instructions.append("serve in " + glass_id + " glass")
                    prepare_instructions.append("fill halfway with ice")
                else:
                    prepare_instructions.append(glass_id_ext + " " + glass_id)
            else:
                prepare_instructions.append("serve in " + ", ".join(glasses))

            state = None
            is_first_line = True
            for i, line in enumerate(f):
                portion = None
                ingredient = None
                line = line.strip()
                if not line: continue

                #if is_first_line:
                #    is_first_line = False
                #    if line.startswith("In "):
                #        continue

                if line.startswith("{{"):
                    continue

                line = line.replace("Cr De Cacao", "Crème De Cacao")
                line = line.replace("Cr De Menthe", "Crème De Menthe")

                if line.startswith("Juice of "):
                    line = line[9:].lower() + " juiced"
                if line.startswith(("Dash ", "Drop ")):
                    line = "1 " + line.lower()

                if line == "Shoot":
                    consume_instructions.append("Shoot")
                    continue
                elif line == "Suck":
                    continue
                elif line == "Swish In Mouth":
                    consume_instructions.append("Swish in mouth")
                    continue
                elif line == "Sugared Lemon Wedge":
                    add_ingredient("lemon")
                    add_ingredient("sugar")
                    prepare_instructions.append("Slice and sugar lemon wedge")
                    consume_instructions.append("Suck lemon wedge")
                    continue

                line = re.sub(r"\[genericingredient ([^]]+)] \1", r"\1", line)
                line = re.sub(r"(?i)\[genericingredient ([^]]+)] Lairds Apple Jack", r"\1", line)
                line = re.sub(r"(?i)creme de \[genericingredient cassis\] hiram walker cr de cassis", r"crème de cassis", line)
                line = re.sub(r"(?i)\[genericingredient Strawberry Schnapps\] Hiram Walker Creme De Strawberry", r"strawberry schnapps", line)
                line = re.sub(r"(?i)\[genericingredient Gold Tequila\] Sauza Anejo Tequila", r"tequila (gold)", line)
                line = re.sub(r"(?i)\[genericingredient ([^]]+)] Hiram Walker Blackberry Liqueur", r"\1", line)
                line = re.sub(r"(?i)\[genericingredient ([^]]+)] Hiram Walker cr de banana", r"\1", line)
                brands = ("Glenlivet", "Goldschlager", "Harveys", "Jack Daniels", "Jameson", "Jim Beam", "Jose Cuervo", "Kahlua", "Malibu", "Martell", "Sauza Anejo", "Hiram Walker", "Ocean Spray", "Beefeater", "Absolut", "Don Pedro", "Baileys", "MUMM")
                line = re.sub(r"(?i)\[genericingredient ([^]]+)] (?:" + "|".join(re.escape(b) for b in brands) + r") \1", r"\1", line)

                line = re.sub(r"(?i)\b(c)reme de ", r"\1rème de ", line)
                line = re.sub(r"(?i)\bjack daniels\b", "whiskey", line)
                line = re.sub(r"(?i)\bsouthern comfort\b", "whiskey", line)
                line = re.sub(r"(?i)\b(rum) (dark) jamacian\b", r"\1 (\2)", line)
                line = re.sub(r"(?i)\b(rum) jamacian\b", r"\1", line)
                line = re.sub(r"(?i)\b(tequilla) premium\b", r"\1 (\2)", line)
                line = re.sub(r"(?i)\b(rum) (light)\b", r"\1", line)
                line = re.sub(r"(?i)\b(rum) (premium)\b", r"\1", line)
                line = re.sub(r"(?i)\b(spiced) (rum)\b", r"\2 (\1)", line)
                line = re.sub(r"(?i)\b(rum) (dark)\b", r"\1 (\2)", line)
                line = re.sub(r"(?i)\b(stout) (beer)\b", r"\2 (\1)", line)
                line = re.sub(r"(?i)\b(white|dark|green) (crème de \w+)\b", r"\2 (\1)", line)

                line = re.sub(r"(?i)\[genericingredient ([^]]+)] Absolut \1", r"\1", line)

                if line == "In Blender,No Ice add" or line == "In Blender-No Ice add":
                    state = "add {} to a blender"
                    state_popper = "blend"
                    continue
                elif line == "In Blender With Ice add":
                    state = "add {} to a blender"
                    prepare_instructions.append(state.format("ice"))
                    #state_popper = "blend"     # "Orangatang"
                    continue
                elif line == "In Mixing Glass With Ice Add:":
                    state = "add {} to a mixing glass"
                    prepare_instructions.append(state.format("ice"))
                    state_popper = None
                    continue
                elif line == "In Mixing Glass,No Ice add":
                    state = "add {} to a mixing glass"
                    state_popper = None
                    continue
                elif line == "In Mixing Glass,No Ice Add:":
                    state = "add {} to a mixing glass"
                    state_popper = None
                    continue
                elif line == "Layer Ingredients":
                    state = "layer {}"
                    state_popper = None
                    continue


                if line.startswith(("3/4 Fill ", "2/3 Fill ", "1/3 Fill ", "1/2 Fill ", "Fill ", "Shake ", "Blend ", "Stir", "Splash ", "Garnish: ", "Top: ", "Float: ", "Gently Stir", "Mash", "Layer ", "In Mixing Glass With Ice Add:",)):
                    if state is not None and state_popper is not None:
                        prepare_instructions.append(state_popper)
                    #state = 
                    if line.endswith(":"):
                        raise ValueError(line)
                    
                    if line.startswith(("3/4 Fill ", "2/3 Fill ", "1/3 Fill ", "1/2 Fill ")):
                        prepare_instructions.append(line.lower())
                        if line[9:].lower() not in ("hot water", "ice"):
                            add_ingredient(nicemap.get(line[9:].lower(), line[9:].lower()))
                    elif line == "Garnish: Sprinkle Nutmeg":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("nutmeg")
                    elif line == "Float: 1/4 oz Grand Marnier":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("grand marnier")
                    elif line == "Garnish: Mint Sprig":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("mint")
                    elif line == "Garnish: Lemon Twist":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lemon")
                    elif line == "Garnish: Pineapple":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("pineapple")
                    elif line == "Garnish: Peanuts":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("peanuts")
                    elif line == "Garnish: Cinnamon Stick":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("cinnamon (stick)")
                    elif line == "Garnish: Slice Green Apple":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("apple (green)")
                    elif line == "Garnish: Cinnamon":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("cinnamon (ground)")
                    elif line == "Garnish: Black Olive":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("olives")
                    elif line == "Garnish: Olive":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("olives")
                    elif line == "Garnish: Chocolate Sprinkles":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("chocolate sprinkles")
                    elif line == "Garnish: Peach Slice":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("peach")
                    elif line == "Garnish: Pearl Onion":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("pearl onion")
                    elif line == "Garnish: Marshmallows":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("marshmallows")
                    elif line == "Garnish: Strawberry":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("strawberry")
                    elif line == "Garnish: Cherry":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("cherry")
                    elif line == "Garnish: Lemon Wheel":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lemon")
                    elif line == "Garnish: Lemon Peel":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lemon")
                    elif line == "Garnish: Lemon Wedge":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lemon")
                    elif line == "Garnish: Lemon Slice":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lemon")
                    elif line == "Garnish: Lime Twist":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lime")
                    elif line == "Garnish: Lime Squeeze":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lime")
                    elif line == "Garnish: Orange Twist":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("orange")
                    elif line == "Garnish: Lime Wedge":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lime")
                    elif line == "Garnish: Lime Slice":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("lime")
                    elif line == "Garnish: Celery":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("celery")
                    elif line == "Garnish: Orange Slice":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("orange")
                    elif line.startswith("Float") and "[" not in line:
                        prepare_instructions.append(line.replace(":", " ").lower().replace("  ", " "))

                        m = re.search(r"(?i)([\d/ ]+)? ?(oz|tsp|scoops|scoop|dashes|dash|tbsp|drop) (.*)", line)
                        if m:
                            portion = m.group(1) + " " + m.group(2)
                            ingredient = m.group(3)
                            add_ingredient(m.group(3).lower())
                            #prepare_instructions.append("float " + portion + " " + ingredient.lower() + " on top")
                        else:
                            m = re.match(r"Float:? ([\w ]+)$", line)
                            if m:
                                add_ingredient(m.group(1).lower())
                                #prepare_instructions.append("float " + m.group(1).lower())
                            else:
                                raise ValueError(repr(line))
                    elif line.startswith("Top: ") and "[" not in line:
                        prepare_instructions.append(line.replace(":", " ").lower().replace("  ", " "))

                        m = re.match(r"(?i)top:? *([\d/ ]+) ?(oz|tsp|scoops|splash|scoop|dashes|dash|tbsp|drop) (.*)", line)
                        if m:
                            portion = m.group(1) + " " + m.group(2)
                            ingredient = m.group(3)
                            add_ingredient(nicemap.get(m.group(3).lower(), m.group(3).lower()))
                            #prepare_instructions.append("top with " + portion + " " + ingredient.lower())
                        else:
                            m = re.match(r"[Tt]op:? ([^0-9].*)", line)
                            if m and m.group(1).lower() != "top":
                                add_ingredient(nicemap.get(m.group(1).lower(), m.group(1).lower()))
                                #prepare_instructions.append("top with " + m.group(1).lower())
                            else:
                                raise ValueError(repr(line))
                    elif line == "Top: 1 oz [genericingredient Coffee Liqueur] Kahlua Coffee Liqueur":
                        prepare_instructions.append("top with 1 oz coffee liqueur (like Kahlua)")
                        add_ingredient("coffee liqueur")
                    elif line == "Top: [genericingredient Sambuca] Hiram Walker Sambuca":
                        prepare_instructions.append("top with sambuca")
                        add_ingredient("sambuca")
                    elif line == "Top: Splash Champagne":
                        prepare_instructions.append("top with splash champagne")
                        add_ingredient("champagne")
                    elif line == "Top: Dash [genericingredient Dark Crème De Cacao] Hiram Walker Dark Crème De Cacao":
                        prepare_instructions.append("top with dash of crème de cacao")
                        add_ingredient("crème de cacao (dark)")
                    elif line == "Top: 2 tsp Creme De [genericingredient Cassis] Hiram Walker Cr De Cassis":
                        prepare_instructions.append("top with 2 tsp crème de cassis")
                        add_ingredient("crème de cassis")
                    elif line == "Top: 1/3 oz Creme De [genericingredient Cassis] Hiram Walker Cr De Cassis":
                        prepare_instructions.append("top with 1/3 oz crème de cassis")
                        add_ingredient("crème de cassis")
                    elif line == "Top: 1/2 oz [genericingredient Melon Liqueur] Hiram Walker Melon Liqueur":
                        prepare_instructions.append("top with mellon liqueur")
                        add_ingredient("mellon liqueur")
                    elif line == "Top: 1 1/2 oz [genericingredient Amaretto] Hiram Walker Amaretto":
                        prepare_instructions.append("top with amaretto")
                        add_ingredient("amaretto")
                    elif line == "Top: [genericingredient Champagne] MUMM Champagne":
                        prepare_instructions.append("top with champagne")
                        add_ingredient("champagne")
                    elif line == "Top: [genericingredient cranberry juice] Ocean Spray Cranberry Juice":
                        prepare_instructions.append("top with cranberry juice")
                        add_ingredient("cranberry juice")
                    elif line == "Top: 1 oz Jack Daniels":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("whiskey")
                    elif line == "Top: [genericingredient Amaretto] Hiram Walker Amaretto":
                        prepare_instructions.append("top with amaretto")
                        add_ingredient("amaretto")
                    elif line == "Top: 1/2 oz [genericingredient Sloe Gin] Hiram Walker Sloe Gin":
                        prepare_instructions.append("top with 1/2 oz sloe gin")
                        add_ingredient("sloe gin")
                    elif line == "Top: 1/2 oz Chambord Raspberry Schnapps":
                        prepare_instructions.append(line.replace(":", " with").lower())
                        add_ingredient("raspberry schnapps")
                    elif line == "Fill Grapefruit Juice":
                        prepare_instructions.append("fill with grapefruit juice")
                        add_ingredient("grapefruit juice")
                    elif line == "Fill Champagne":
                        prepare_instructions.append("fill with champagne")
                        add_ingredient("champagne")
                    elif line == "Fill Coffee":
                        prepare_instructions.append("fill with coffee")
                        add_ingredient("coffee")
                    elif line == "Fill Bloody Mary Mix":
                        prepare_instructions.append("fill with bloody-mary mix")
                        add_ingredient("bloody mary mix")
                    elif line == "Fill Hot Chocolate":
                        prepare_instructions.append("fill with hot chocolate")
                        add_ingredient("hot chocolate")
                    elif line == "Fill Pineapple Juice":
                        prepare_instructions.append("fill with pineapple juice")
                        add_ingredient("pineapple juice")
                    elif line == "Fill Cola":
                        prepare_instructions.append("fill with cola")
                        add_ingredient("cola")
                    elif line == "Fill Sweet/Sour Mix":
                        prepare_instructions.append("fill with sweet/sour mix")
                        add_ingredient("sour mix")
                    elif line == "Fill Tonic":
                        prepare_instructions.append("fill with tonic")
                        add_ingredient("tonic")
                    elif line == "Fill Lemonade":
                        prepare_instructions.append("fill with lemonade")
                        add_ingredient("lemonade")
                    elif line == "Fill [genericingredient Champagne] MUMM Champagne":
                        prepare_instructions.append("fill with champagne (like MUMM Champagne)")
                        add_ingredient("champagne")
                    elif line == "Fill Apple Juice":
                        prepare_instructions.append("fill with apple juice")
                        add_ingredient("apple juice")
                    elif line == "Fill White Wine":
                        prepare_instructions.append("fill with white wine")
                        add_ingredient("wine (white)")
                    elif line == "Fill Water":
                        prepare_instructions.append("fill with water")
                    elif line == "Fill Root Beer":
                        prepare_instructions.append("fill with root beer")
                        add_ingredient("root beer")
                    elif line == "Fill Lime Soda":
                        prepare_instructions.append("fill with lime soda")
                        add_ingredient("lime soda")
                    elif line == "Fill Lemon Lime Soda":
                        prepare_instructions.append("fill with lemon lime soda (like Sprite)")
                        add_ingredient("lemon lime soda")
                    elif line == "Fill Milk":
                        prepare_instructions.append("fill with milk")
                        add_ingredient("milk")
                    elif line == "Fill Orange Juice":
                        prepare_instructions.append("fill with orange juice")
                        add_ingredient("orange juice")
                    elif line == "Fill cranberry juice":
                        prepare_instructions.append("fill with cranberry juice")
                        add_ingredient("cranberry juice")
                    elif line == "Fill Coffee":
                        prepare_instructions.append("fill with coffee")
                        add_ingredient("coffee")
                    elif line == "Fill Beer":
                        prepare_instructions.append("fill with beer")
                        add_ingredient("beer")
                    elif line == "Fill Cream":
                        prepare_instructions.append("fill with cream")
                        add_ingredient("cream")
                    elif line == "Fill Ginger Ale":
                        prepare_instructions.append("fill with ginger ale")
                        add_ingredient("ginger ale")
                    elif line == "Fill Club Soda":
                        prepare_instructions.append("fill with club soda")
                        add_ingredient("club soda")
                    elif line == "Fill Hot Water":
                        prepare_instructions.append("fill with hot water")
                    elif line == "Fill Cold Coffee":
                        prepare_instructions.append("fill with cold coffee")
                        add_ingredient("coffee")
                    elif line == "Fill with Ice":
                        prepare_instructions.append("fill with ice")
                    elif line == "Shake and Strain":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Mash with Spoon":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Gently Stir":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Stir":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Blend and Strain":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Blend and Pour":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Shake and Pour":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Shake and Pour":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Gently Stir and Strain":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Stir and Strain":
                        if state_popper is not None: prepare_instructions.append(state_popper); state_popper = None
                        prepare_instructions.append(line.lower())
                    elif line == "Splash Water":
                        prepare_instructions.append(line.lower())
                    elif line.startswith("Splash "):
                        prepare_instructions.append(line.lower())
                        add_ingredient(nicemap.get(line[7:].lower(), line[7:].lower()))
                    else:
                        raise ValueError(drink_number, line)
                    continue

                if line == "Salted Rim Optional":
                    prepare_instructions.append("optionally, salt rim")
                    continue

                if line == "3 Sour Cherries":
                    prepare_instructions.append("add 3 sour cherries")
                    add_ingredient("sour cherries")
                    continue

                if line == "3 Mint Leaves":
                    prepare_instructions.append("add 3 mint leaves")
                    add_ingredient("mint")
                    continue
                    
                if line == "1 Orange Slice":
                    prepare_instructions.append("add orange slice")
                    add_ingredient("orange")
                    continue

                if line == "Sugar Rim":
                    prepare_instructions.append("sugar rim")
                    add_ingredient("sugar")
                    continue

                if line == "1/4 Fill Ice":
                    prepare_instructions.append("fill 1/4 ice")
                    continue

                if line == "Ice":
                    prepare_instructions.append("add ice")
                    continue

                if line == "Cola":
                    prepare_instructions.append("add cola")
                    add_ingredient("cola")
                    continue

                m = re.match(r"(?i)([\d/ ]+) (Lemon|Lime|Egg|Egg White)", line)
                if m:
                    portion = m.group(1)
                    ingredient = m.group(2)
                    long_ingredient = None
                else:
                    m = re.match(r"(?i)([\d/ ]+) (oz|tsp|scoops|scoop|dashes|dash|tbsp|drop) (.*)", line)
                    if m:
                        portion = m.group(1) + " " + m.group(2)
                        ingredient = m.group(3)
                        long_ingredient = None

                        m = re.match(r"\[genericingredient ([^]]*)\] (.*)", ingredient)
                        if m:
                            if m.group(1).lower() == m.group(2).lower():
                                ingredient = m.group(1)
                            else:
                                ingredient = m.group(1)
                                long_ingredient = m.group(2)
                    else:
                        raise MakesNoSense(line)

                if ingredient is not None:
                    if ingredient.lower() == "lemon juice":
                        add_ingredient("lemon")
                    elif ingredient.lower() == "lime juice":
                        add_ingredient("lime")
                    elif ingredient.lower() == "water":
                        pass
                    else:
                        ingred = ingredient.lower()
                        add_ingredient(nicemap.get(ingred, ingred))

                if ingredient:
                    if state is not None:
                        if long_ingredient:
                            prepare_instructions.append(state.format(ingredient.lower() + " (like " + long_ingredient + ")"))
                        else:
                            prepare_instructions.append("add " + portion + " of " + ingredient.lower())
                    else:
                        if long_ingredient:
                            prepare_instructions.append("add " + portion + " of " + ingredient.lower() + " (like " + long_ingredient + ")")
                        else:
                            prepare_instructions.append("add " + portion + " of " + ingredient.lower())
                else:
                    raise MakesNoSense(line)

            for ingredient in ingredients:
                n = ingredient_frequency.get(ingredient, 0)
                n += 1
                ingredient_frequency[ingredient] = n
                    
            all_ingredients |= ingredients

        except MakesNoSense as ex:
            print(repr(filename), ex)
            continue


        description["name"] = filename
        description["prepare_instructions"] = [fraction_pretify(pi) for pi in prepare_instructions]
        if consume_instructions:
            description["consume_instructions"] = consume_instructions
        description["ingredients"] = list(ingredients - set(["ice", "water", "hot water", "float", "top"]))
        description["glasses"] = list(glasses)
        recipe_book.append(description)


sorted_ingredients = list(k for v, k in reversed(sorted((v, k) for k, v in ingredient_frequency.items())))

white_russian = [d for d in recipe_book if d["name"] == "White Russian"][0]
assert "serve in rocks glass" in white_russian["prepare_instructions"]
assert "cream" in white_russian["ingredients"]
assert "coffee liqueur" in white_russian["ingredients"]
assert "vodka" in white_russian["ingredients"]

for d in recipe_book:
    assert "top" not in d["ingredients"], d
    assert "float" not in d["ingredients"], d

with open("drinks.json.gz.fakeheader", "wb") as f:
    struct = [3, datetime.utcnow().strftime("%s"), canonical_ingredients, recipe_book, sorted_ingredients[:17]]

    f.write(b"\x78\x9c\xec\xbdY\xcf\xf8\0\0\0CM\0\1\5\7cinnamon+(ground)rum+(dark)sambu\x10")
    f.write(b"$!@wef3\xf4(8wF34hALwef3\xf4\xca\x9a")
    f.write(b"$!@(8wF34hALwwef3\xf4ef3\xf4\xaa\x3a")
    f.write(b"garnisheshalwef3\xf4\xaawef3\xf4\x77")
    f.write(b"#creamlemonlwef3\xf4\xca\x9a")
    f.write(b"#!@ginger+aleef3\xf2\xcaef3\xf4\x21")
    f.write(b"cognaclimecolaf3\xf4\xcaef3\xf4\x22")
    f.write(b"#celeryabsintye3\xf4\xcaef3\xf4\x23")
    f.write(b"#!@amarettotonic\xf2\xcaef3\xf4\x24")
    f.write(b" #!@(8tequilawef3\xf2\xcaef3\xf4\x25")
    z = json.dumps(struct, indent=1)
    z = gzip.compress(z.encode("latin1"), 9)
    f.write(z)

